-- CREATE SCHEMAS
CREATE SCHEMA newsbag_core;
CREATE SCHEMA newsbag_user1;
CREATE SCHEMA newsbag_user2;

-- CREATE ARTICLES SQL SCRIPT
CREATE TABLE newsbag_core.articles(
	id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	body TEXT(65535) NOT NULL,
	createTime INT NOT NULL,
    	authorId INT NOT NULL,
	categoryId INT NOT NULL,
	PRIMARY KEY (id)
);

-- CREATE CATEGORIES SQL SCRIPT
CREATE TABLE newsbag_core.categories(
	id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(30) NOT NULL,
	PRIMARY KEY(id)
);

-- CREATE USERS SQL SCRIPT
CREATE TABLE newsbag_core.users(
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(30) NOT NULL,
	PRIMARY KEY(id)
);

-- CREATE COMMENTS SQL SCRIPT
CREATE TABLE newsbag_core.comments(
	id INT NOT NULL AUTO_INCREMENT,
	userId INT NOT NULL,
	articleId INT NOT NULL,
	text VARCHAR(250) NOT NULL,
	PRIMARY KEY(id)
);

-- CREATE RATINGS SQL SCRIPT
CREATE TABLE newsbag_core.ratings(
	id INT NOT NULL AUTO_INCREMENT,
	userId INT NOT NULL,
	articleId INT NOT NULL,
	value INT NOT NULL,
	PRIMARY KEY(id)
);